# Generated by Django 5.0.6 on 2024-05-15 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0023_rename_publicsource_encode_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cellline",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="cellmarker",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="celltype",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="developmentalstage",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="ethnicity",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="experimentalfactor",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="organism",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="pathway",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="phenotype",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="protein",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="tissue",
            name="collections",
        ),
    ]
