# Generated by Django 5.2 on 2024-11-15 16:15

import django.db.models.deletion
import lnschema_core.fields
import lnschema_core.models
import lnschema_core.users
from django.db import migrations, models

import bionty.ids

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# bionty.migrations.0032_rename_source_name_source_description_and_more


class Migration(migrations.Migration):
    replaces = [
        ("bionty", "0028_squashed"),
        ("bionty", "0029_alter_cellline_previous_runs_and_more"),
        ("bionty", "0030_rename_publicsource_source_and_more"),
        ("bionty", "0031_alter_cellmarker_name_and_more"),
        ("bionty", "0032_rename_source_name_source_description_and_more"),
        ("bionty", "0033_alter_artifactcellline_artifact_and_more"),
        ("bionty", "0034_alter_source_unique_together"),
        ("bionty", "0035_alter_protein_gene_symbol"),
        ("bionty", "0036_alter_source_artifacts_and_more"),
        ("bionty", "0037_alter_cellline_source_alter_cellmarker_source_and_more"),
        ("bionty", "0038_alter_artifactcellline_created_by_and_more"),
        ("bionty", "0039_alter_cellline_source_alter_cellmarker_source_and_more"),
        (
            "bionty",
            "0040_rename_feature_ref_is_symbol_artifactgene_feature_ref_is_name_and_more",
        ),
        ("bionty", "0041_alter_artifactcellline_artifact_and_more"),
    ]

    dependencies = [
        ("lnschema_core", "0052_squashed"),
        ("lnschema_core", "0054_alter_feature_previous_runs_and_more"),
        ("lnschema_core", "0055_artifact_type_artifactparamvalue_and_more"),
        (
            "lnschema_core",
            "0056_rename_ulabel_ref_is_name_artifactulabel_label_ref_is_name_and_more",
        ),
        ("lnschema_core", "0060_alter_artifact__actions"),
        ("lnschema_core", "0066_alter_artifact__feature_values_and_more"),
        ("lnschema_core", "0067_alter_featurevalue_unique_together_and_more"),
        (
            "lnschema_core",
            "0069_alter_artifact__accessor_alter_artifact__hash_type_and_more",
        ),
    ]
