# Generated by Django 5.2 on 2025-01-13 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bionty", "0044_alter_cellline_space_alter_cellmarker_space_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cellline",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="cellmarker",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="celltype",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="developmentalstage",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="disease",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="ethnicity",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="experimentalfactor",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="gene",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="organism",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="pathway",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="phenotype",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="protein",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="aux",
            new_name="_aux",
        ),
        migrations.RenameField(
            model_name="tissue",
            old_name="aux",
            new_name="_aux",
        ),
    ]
