# Generated by Django 5.2 on 2025-02-16 21:50

import lamindb.base.fields
from django.db import migrations

import bionty.ids


class Migration(migrations.Migration):
    dependencies = [
        ("bionty", "0049_alter_schemacellmarker_cellmarker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True, default=bionty.ids.source, max_length=8, unique=True
            ),
        ),
    ]
