# Generated by Django 5.1.12 on 2025-09-29 00:46

import lamindb.base.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bionty", "0058_cellline_page_cellmarker_page_celltype_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellline",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="cellmarker",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="celltype",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="developmentalstage",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="disease",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="experimentalfactor",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="gene",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="organism",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="pathway",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="phenotype",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="protein",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="source",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="tissue",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(blank=True, default=False),
        ),
    ]
