# Generated by Django 5.1.12 on 2025-09-29 07:51

import lamindb.base.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bionty", "0059_cellline_is_locked_cellmarker_is_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellline",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="cellmarker",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="celltype",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="developmentalstage",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="ethnicity",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="experimentalfactor",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="gene",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="organism",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="pathway",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="phenotype",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="tissue",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
    ]
