# Generated by Django 5.2 on 2026-01-05 11:15

import django.db.models.deletion
import lamindb.base.fields
from django.db import migrations


def rename_branch_columns(apps, schema_editor):
    """Rename _branch_code to branch_id across all models."""
    tables = [
        "bionty_cellline",
        "bionty_cellmarker",
        "bionty_celltype",
        "bionty_developmentalstage",
        "bionty_disease",
        "bionty_ethnicity",
        "bionty_experimentalfactor",
        "bionty_gene",
        "bionty_organism",
        "bionty_pathway",
        "bionty_phenotype",
        "bionty_protein",
        "bionty_source",
        "bionty_tissue",
    ]

    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "postgresql":
            for table in tables:
                cursor.execute(
                    f"ALTER TABLE {table} RENAME COLUMN _branch_code TO branch_id;"
                )

        elif schema_editor.connection.vendor == "sqlite":
            # SQLite 3.25.0+ supports ALTER TABLE RENAME COLUMN
            for table in tables:
                try:
                    cursor.execute(
                        f"ALTER TABLE {table} RENAME COLUMN _branch_code TO branch_id;"
                    )
                except Exception as error:
                    raise NotImplementedError(
                        "This migration requires SQLite 3.25.0 or newer. "
                        "Please upgrade SQLite or manually recreate the tables."
                    ) from error


class Migration(migrations.Migration):
    dependencies = [
        ("bionty", "0061_remove_cellline_page_remove_cellmarker_page_and_more"),
        ("lamindb", "0161_rename_branch_code_to_branch_id"),
    ]

    operations = [
        # Rename the columns at the database level
        migrations.RunPython(
            rename_branch_columns,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="artifactcellline",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcellline",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcellmarker",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcellmarker",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcelltype",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcelltype",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactdevelopmentalstage",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactdevelopmentalstage",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactdisease",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactdisease",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactethnicity",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactethnicity",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactexperimentalfactor",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactexperimentalfactor",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactgene",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactgene",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactorganism",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactorganism",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactpathway",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactpathway",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactphenotype",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactphenotype",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactprotein",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactprotein",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifacttissue",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifacttissue",
            name="label_ref_is_name",
        ),
        # Update Django's state only (no database operations)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="cellline",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="cellmarker",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="celltype",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="developmentalstage",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="disease",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="ethnicity",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="experimentalfactor",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="gene",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="organism",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="pathway",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="phenotype",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="protein",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="source",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="tissue",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
            ],
        ),
    ]
